language: r
sudo: false
cache: packages
warnings_are_errors: true

r_binary_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
