# modified from Yihui's code for knitr
language: python

# environment variables
env:
  - R_LIBS_USER=~/R

# install dependencies
install:
  - sudo apt-add-repository -y ppa:marutter/rdev
  - sudo apt-get update
  - sudo apt-get install r-base-dev
  - "[ ! -d ~/R ] && mkdir ~/R"
  - R --version
  - R -e '.libPaths(); sessionInfo()'
  - Rscript -e 'install.packages(c("ggplot2","plyr","png","httr","RJSONIO","RCurl","ape","adephylo","devtools"), repos = "http://cran.rstudio.org"); library(devtools); install_github("ggphylo","gjuggler"); install_github("fylopic","schamberlain")'

# run tests
script:
  - make install
  - make check